FROM arm32v7/python:3.9-buster

WORKDIR /app

COPY . /app/plant_watering
WORKDIR /app/plant_watering

RUN pip install  --extra-index-url https://www.piwheels.org/simple -r requirements.txt
RUN python setup.py install

WORKDIR /app

ENTRYPOINT ["python", "-m", "plantwatering.run"]